import os

rpathLib = Dir('#/lib')

include = Dir('#/include')
picoscopeInclude = Dir('/opt/picoscope/include')
picoscopeDriver = Dir('/opt/uvahep/include')
env = Environment(LIBS=['libpicoscopeInterface', 'Spectrum', 'ps5444b', 'ps5000a'], CCFLAGS=' -ggdb  -std=c++11', CPPPATH=[include, picoscopeInclude, picoscopeDriver], LIBPATH=['#/lib', '/opt/uvahep/lib', '/opt/picoscope/lib', '.'])

env.Append(RPATH = str(Dir('/opt/uvahep/lib')))
try:
    env.ParseConfig("root-config --cflags --libs")
except:
    env.PrependENVPath('PATH','~/root/bin')

    env.ParseConfig("root-config --cflags --libs")

## Generate Root Dictionary File 
cintBuilder = Builder(action = 'rootcint -f $TARGET -c $SOURCES')
env.Append(BUILDERS= {'cint': cintBuilder})

env.Alias('install','/opt/uvahep/bin')
env.Program('darkBuffers', ['darkBuffers.cc', 'utils.cc'])
env.Program('pulseMeasurements', ['pulseMeasurements.cc'])

